### ISSUE TITLE
Marker-based Mocap data

### ISSUE THREAD

**Issue by zhihaolee** [ChenFengYe/SportsCap#1]
Are there paired images for the marker-based mocap data?

**Comment by ChenFengYe** [comment]
For these marker-based mocap data, the performaners are dressed with black Mocap suit. Therefore, we do not capture these paired images. Sorray about that.

If you are intersted in the paired images and 3D motion data.  For monocular setting, I recommand [3DPW](https://paperswithcode.com/dataset/mpi-inf-3dhp) or [Human36](http://vision.imar.ro/human3.6m/description.php)
Feel free to ask, if you have more questions.
