### ISSUE TITLE
Hi, I'm planning to do article reproduction

### ISSUE THREAD

**Issue by smallwhite-dragon** [ChenFengYe/SportsCap#2]
If you see it, can you private message me and I would like to get in touch with you for some help. Thank you very much.

**Comment by ChenFengYe** [comment]
Hi, thank you for your interest in our work. I will try my best to help you. Could you please email me your Wechat for better communication?

**Comment by smallwhite-dragon** [comment]
18031985229

**Comment by smallwhite-dragon** [comment]
wxid_ej90n4i5p02w22

**Comment by smallwhite-dragon** [comment]
Hi，18031985229，please call me
